# Generated by Django 4.1.5 on 2023-01-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exptedientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exptediente', models.CharField(max_length=20)),
                ('Nombre_Causante', models.CharField(max_length=20)),
                ('Apellido_Causante', models.CharField(max_length=20)),
                ('DNI', models.CharField(max_length=10)),
            ],
        ),
    ]
